[profile.default]
src = "src"
out = "out"
libs = ["lib", "dependencies"]
solc = "0.8.27"
remappings = [
    "forge-std/=dependencies/forge-std-1.9.2/src/"
]

[dependencies]
forge-std = { version = "1.9.2", git = "https://github.com/foundry-rs/forge-std.git", rev = "60acb7aaadcce2d68e52986a0a66fe79f07d138f" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
